version: "3.9"
services:
  postgres:
    ports:
      - '5436:5432'
    restart: always
    image: postgres:9.6.5-alpine
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh

  mongo:
    image: mongo:4.4.3-bionic
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
